-- MySQL Script generated by MySQL Workbench
-- 02/22/18 16:00:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ErBanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ErBanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ErBanco` DEFAULT CHARACTER SET utf8 ;
USE `ErBanco` ;

-- -----------------------------------------------------
-- Table `ErBanco`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Rol` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Rol` (
  `RolID` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`RolID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Usuario` (
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `RolID` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `HashContrasena` VARCHAR(45) NOT NULL,
  `FechaCreacion` VARCHAR(45) NOT NULL,
  `FechaModificacion` VARCHAR(45) NOT NULL,
  `FechaBaja` VARCHAR(45) NULL,
  PRIMARY KEY (`NombreUsuario`),
  INDEX `idRol_idx` (`RolID` ASC),
  CONSTRAINT `RolID`
    FOREIGN KEY (`RolID`)
    REFERENCES `ErBanco`.`Rol` (`RolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`Permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Permiso` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Permiso` (
  `PermisoID` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`PermisoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`Permiso_Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Permiso_Rol` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Permiso_Rol` (
  `PermisoID` VARCHAR(45) NOT NULL,
  `RolID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PermisoID`, `RolID`),
  INDEX `idRol_idx` (`RolID` ASC),
  CONSTRAINT `PermisoID_C`
    FOREIGN KEY (`PermisoID`)
    REFERENCES `ErBanco`.`Permiso` (`PermisoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RolID_C`
    FOREIGN KEY (`RolID`)
    REFERENCES `ErBanco`.`Rol` (`RolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Cuenta` (
  `NumeroCuenta` VARCHAR(45) NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Saldo` DECIMAL(45) NOT NULL,
  `LimiteDiario` DECIMAL(45) NULL,
  `LimiteInferior` DECIMAL(45) NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `FechaModificacion` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`NumeroCuenta`),
  INDEX `NombreUsuario_idx` (`NombreUsuario` ASC),
  CONSTRAINT `NombreUsuario`
    FOREIGN KEY (`NombreUsuario`)
    REFERENCES `ErBanco`.`Usuario` (`NombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`Tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Tarjeta` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Tarjeta` (
  `NumeroTarjeta` VARCHAR(45) NOT NULL,
  `PIN` VARCHAR(45) NOT NULL,
  `FechaCaducidad` DATETIME NULL,
  `Titular` VARCHAR(45) NULL,
  `LimiteDiario` DECIMAL(45) NULL,
  `FechaCreacion` VARCHAR(45) NULL,
  `FechaBaja` DATETIME NULL,
  `FechaCancelacion` DATETIME NULL,
  `Discriminador` VARCHAR(45) NULL,
  `NumeroCuenta` VARCHAR(45) NULL,
  `NombreUsuario` VARCHAR(45) NULL,
  `Saldo` DECIMAL(45) NULL,
  `LimiteSuperior` DECIMAL(45) NULL,
  PRIMARY KEY (`NumeroTarjeta`),
  INDEX `NumeroCuenta_idx` (`NumeroCuenta` ASC),
  CONSTRAINT `NumeroCuenta_C1`
    FOREIGN KEY (`NumeroCuenta`)
    REFERENCES `ErBanco`.`Cuenta` (`NumeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NombreUsuario_C2`
    FOREIGN KEY (`NombreUsuario`)
    REFERENCES `ErBanco`.`Usuario` (`NombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`TarjetaCredito`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `ErBanco`.`TarjetaCredito` ;

-- CREATE TABLE IF NOT EXISTS `ErBanco`.`TarjetaCredito` (
-- )
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`TajetaDebito`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `ErBanco`.`TajetaDebito` ;

-- CREATE TABLE IF NOT EXISTS `ErBanco`.`TajetaDebito` (
-- )
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`TarjetaMonedero`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `ErBanco`.`TarjetaMonedero` ;

-- CREATE TABLE IF NOT EXISTS `ErBanco`.`TarjetaMonedero` (
-- )
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ErBanco`.`Operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErBanco`.`Operacion` ;

CREATE TABLE IF NOT EXISTS `ErBanco`.`Operacion` (
  `OperacionID` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Cantidad` DECIMAL(45) NOT NULL,
  `NumeroCuentaOrigen` VARCHAR(45) NULL,
  `NumeroCuentaDestino` VARCHAR(45) NULL,
  `NumeroTarjeta` VARCHAR(45) NULL,
  `Discriminador` VARCHAR(45) NULL,
  `CantidadFinal` DECIMAL(45) NULL,
  PRIMARY KEY (`OperacionID`),
  INDEX `NumeroCuentaOrigen_idx` (`NumeroCuentaOrigen` ASC),
  INDEX `NumeroCuentaDestino_idx` (`NumeroCuentaDestino` ASC),
  INDEX `NumeroTarjeta_idx` (`NumeroTarjeta` ASC),
  CONSTRAINT `NumeroCuentaOrigen_C`
    FOREIGN KEY (`NumeroCuentaOrigen`)
    REFERENCES `ErBanco`.`Cuenta` (`NumeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NumeroCuentaDestino_C`
    FOREIGN KEY (`NumeroCuentaDestino`)
    REFERENCES `ErBanco`.`Cuenta` (`NumeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NumeroTarjeta_C`
    FOREIGN KEY (`NumeroTarjeta`)
    REFERENCES `ErBanco`.`Tarjeta` (`NumeroTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
